### ISSUE TITLE
Define Milestone 0

### ISSUE THREAD

**Issue by SashkoTar** [SashkoTar/syto#8]
- [ ] Define name conventions, versioning
- [ ] Define expected functionality
- [ ] Define filter types and approximations
- [ ] Set up deadlines and goals
- [ ] Define metrics to track
